FROM quay.io/runcom/kiosk-base:latest
COPY image.conf /etc/flatpak/installations.d/
RUN rpm-ostree install flatpak && \
  flatpak remote-add --installation=image --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && \
  flatpak install --installation=image -y flathub org.gimp.GIMP
COPY --chmod=0755 --chown=1042:1042 gnome-kiosk-script.flatpak /usr/lib/gnome-kiosk-script
RUN ostree container commit